
-- 1. HABILITAR EXTENSÃO DE UUID (Necessário para IDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CRIAR TABELA DE USUÁRIOS (Atualizado para 'usuarios')
CREATE TABLE IF NOT EXISTS public.usuarios (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    role TEXT NOT NULL,
    condominio_id TEXT,
    password TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. CRIAR TABELA DE PEDIDOS/SOLICITAÇÕES
CREATE TABLE IF NOT EXISTS public.solicitacoes (
    id TEXT PRIMARY KEY,
    condominio_id TEXT NOT NULL,
    condominio_nome TEXT,
    responsavel_nome TEXT,
    data_solicitacao TIMESTAMP WITH TIME ZONE,
    titulo TEXT,
    descricao TEXT,
    tipo TEXT,
    categoria TEXT,
    category_id TEXT, -- LEMBRAR: Alterar para TEXT se usar ids string (ex: 'cat-123')
    nivel TEXT,
    status TEXT,
    orcamentos JSONB DEFAULT '[]'::jsonb,
    historico JSONB DEFAULT '[]'::jsonb,
    attachments JSONB DEFAULT '[]'::jsonb,
    assembly_data JSONB DEFAULT '{}'::jsonb,
    caveats JSONB DEFAULT '[]'::jsonb,
    messages JSONB DEFAULT '[]'::jsonb,
    deadline_days INTEGER,
    due_at TIMESTAMP WITH TIME ZONE,
    estimated_delivery_date TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    sla_vencimento TIMESTAMP WITH TIME ZONE,
    fora_do_prazo BOOLEAN DEFAULT false,
    stock_control_enabled BOOLEAN DEFAULT false,
    stock_generated_at TIMESTAMP WITH TIME ZONE,
    autorizado_por_nome TEXT,
    autorizado_por_cargo TEXT,
    justificativa_condominio TEXT,
    justificativa_recusa TEXT,
    justificativa_encerramento TEXT,
    orcamento_escolhido INTEGER
);

-- 4. CRIAR TABELA DE FORNECEDORES
CREATE TABLE IF NOT EXISTS public.suppliers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    legal_name TEXT,
    active BOOLEAN DEFAULT true,
    activity_branch TEXT,
    contact_name TEXT,
    phone TEXT,
    whatsapp TEXT,
    email TEXT,
    cnpj TEXT,
    supply_type TEXT,
    contract JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. CRIAR TABELAS DE ESTOQUE
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id TEXT PRIMARY KEY,
    condominio_id TEXT NOT NULL,
    name TEXT NOT NULL,
    unit TEXT,
    min_level NUMERIC DEFAULT 0,
    current_qty NUMERIC DEFAULT 0,
    status TEXT,
    category_id TEXT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT REFERENCES public.inventory_items(id),
    condominio_id TEXT,
    type TEXT,
    qty NUMERIC,
    reason TEXT,
    request_id TEXT,
    created_by_role TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. CRIAR TABELA DE CATEGORIAS
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT,
    active BOOLEAN DEFAULT true,
    color TEXT,
    default_type TEXT,
    requires_three_quotes BOOLEAN DEFAULT true,
    requires_evidence BOOLEAN DEFAULT false,
    inventory_enabled BOOLEAN DEFAULT false,
    deadline_day_of_month INTEGER,
    min_quote_business_days INTEGER,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. TABELA DE CONTATOS E CONFIGURAÇÕES
CREATE TABLE IF NOT EXISTS public.contacts (
    id TEXT PRIMARY KEY,
    condominio_id TEXT NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    role TEXT,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.app_settings (
    id TEXT PRIMARY KEY,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.request_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id TEXT,
    condominio_id TEXT,
    alert_type TEXT,
    sent_to_phone TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. CONFIGURAR SEGURANÇA (RLS - Permitir acesso ao App)
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_notifications ENABLE ROW LEVEL SECURITY;

-- Criar políticas de acesso "Públicas" (Ideal para MVP/App Interno)
DROP POLICY IF EXISTS "Allow All Users" ON public.usuarios;
CREATE POLICY "Allow All Users" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Solicitacoes" ON public.solicitacoes;
CREATE POLICY "Allow All Solicitacoes" ON public.solicitacoes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Suppliers" ON public.suppliers;
CREATE POLICY "Allow All Suppliers" ON public.suppliers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Inventory" ON public.inventory_items;
CREATE POLICY "Allow All Inventory" ON public.inventory_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Movements" ON public.inventory_movements;
CREATE POLICY "Allow All Movements" ON public.inventory_movements FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Categories" ON public.categories;
CREATE POLICY "Allow All Categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Contacts" ON public.contacts;
CREATE POLICY "Allow All Contacts" ON public.contacts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Settings" ON public.app_settings;
CREATE POLICY "Allow All Settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Notifications" ON public.request_notifications;
CREATE POLICY "Allow All Notifications" ON public.request_notifications FOR ALL USING (true) WITH CHECK (true);

-- 9. CONFIGURAR ARMAZENAMENTO DE ARQUIVOS (STORAGE)
INSERT INTO storage.buckets (id, name, public) VALUES ('budgets', 'budgets', true) ON CONFLICT (id) DO NOTHING;
DROP POLICY IF EXISTS "Allow All Storage" ON storage.objects;
CREATE POLICY "Allow All Storage" ON storage.objects FOR ALL USING (bucket_id = 'budgets') WITH CHECK (bucket_id = 'budgets');
