
-- =================================================================================
-- CONFIGURAÇÃO DE CONTROLE DE ESTOQUE
-- Rode este script no SQL Editor do Supabase.
-- =================================================================================

-- 1. Adicionar o "Campo de Seleção" na tabela de solicitações
-- Este campo (stock_control_enabled) define se o pedido vai virar estoque ao ser concluído.
ALTER TABLE public.solicitacoes 
ADD COLUMN IF NOT EXISTS stock_control_enabled BOOLEAN DEFAULT false;

ALTER TABLE public.solicitacoes 
ADD COLUMN IF NOT EXISTS stock_generated_at TIMESTAMP WITH TIME ZONE;

-- 2. Criar a tabela de Itens de Estoque (Se não existir)
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id TEXT PRIMARY KEY,
    condominio_id TEXT NOT NULL,
    name TEXT NOT NULL,
    unit TEXT DEFAULT 'un',
    min_level NUMERIC DEFAULT 5,
    current_qty NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'NORMAL', -- 'NORMAL', 'LOW', 'EMPTY'
    category_id TEXT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Criar a tabela de Movimentações (Histórico de Entrada/Saída)
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT REFERENCES public.inventory_items(id),
    condominio_id TEXT,
    type TEXT, -- 'IN' (Entrada), 'OUT' (Saída/Consumo), 'ADJUST' (Ajuste)
    qty NUMERIC,
    reason TEXT,
    request_id TEXT, -- Link com o pedido original (se houver)
    created_by_role TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Habilitar Permissões (RLS) para que o App possa ler e escrever
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

-- Políticas permissivas (para garantir funcionamento do App)
DROP POLICY IF EXISTS "Allow All Inventory" ON public.inventory_items;
CREATE POLICY "Allow All Inventory" ON public.inventory_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow All Movements" ON public.inventory_movements;
CREATE POLICY "Allow All Movements" ON public.inventory_movements FOR ALL USING (true) WITH CHECK (true);

-- Permissão para atualizar a coluna na tabela de solicitações
GRANT UPDATE (stock_control_enabled, stock_generated_at) ON public.solicitacoes TO anon, authenticated, service_role;

-- 5. Atualizar Cache
NOTIFY pgrst, 'reload config';
