
-- =================================================================================
-- CONFIGURAÇÃO DE GESTÃO DE ESTOQUE (AUTOMATIZAÇÃO)
-- Execute este script para garantir que a entrada automática de estoque funcione.
-- =================================================================================

-- 1. Garante que a tabela de Solicitações tem os campos de controle
ALTER TABLE public.solicitacoes 
ADD COLUMN IF NOT EXISTS stock_control_enabled BOOLEAN DEFAULT false;

ALTER TABLE public.solicitacoes 
ADD COLUMN IF NOT EXISTS stock_generated_at TIMESTAMP WITH TIME ZONE;

-- 2. Cria a tabela de Itens de Estoque (Almoxarifado)
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id TEXT PRIMARY KEY,
    condominio_id TEXT NOT NULL,
    name TEXT NOT NULL,
    unit TEXT DEFAULT 'un',
    min_level NUMERIC DEFAULT 5,
    current_qty NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'NORMAL', -- 'NORMAL', 'LOW', 'EMPTY'
    category_id TEXT,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Cria a tabela de Histórico de Movimentações
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT REFERENCES public.inventory_items(id),
    condominio_id TEXT,
    type TEXT, -- 'IN' (Entrada), 'OUT' (Saída), 'ADJUST' (Ajuste)
    qty NUMERIC,
    reason TEXT,
    request_id TEXT, -- Link com o pedido original
    created_by_role TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. SEGURANÇA E PERMISSÕES (CRÍTICO PARA A AUTOMAÇÃO)
-- Habilita RLS
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas para evitar conflitos
DROP POLICY IF EXISTS "Allow All Inventory" ON public.inventory_items;
DROP POLICY IF EXISTS "Allow All Movements" ON public.inventory_movements;

-- Cria políticas permissivas para o App (Leitura e Escrita)
CREATE POLICY "Allow All Inventory" ON public.inventory_items 
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow All Movements" ON public.inventory_movements 
FOR ALL USING (true) WITH CHECK (true);

-- Garante permissões explícitas para as roles do Supabase (anon/authenticated)
GRANT ALL ON public.inventory_items TO anon, authenticated, service_role;
GRANT ALL ON public.inventory_movements TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_movements_id_seq TO anon, authenticated, service_role;

-- 5. Atualiza permissões na tabela de solicitações para permitir marcar como 'estoque gerado'
GRANT UPDATE (stock_control_enabled, stock_generated_at) ON public.solicitacoes TO anon, authenticated, service_role;

-- 6. Recarrega o Cache da API
NOTIFY pgrst, 'reload config';
